# author: Shelby Hendrickx

CC = gcc

CFLAGS = -g -Wall

all: exercise10

exercise10: exercise10.c exercise10-main.c
		$(CC) $(CFLAGS) -o exercise10 exercise10.c exercise10-main.c

clean:
		$(RM) exercise10

